name: build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: run script
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo config.py < `api_key =  "${{ secrets.youtube_api_key }}"`
        python get-nenelist.py
        python main.py
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./api
        publish_bransh: gh-pages
